# Generated by Django 5.2.1 on 2025-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=100)),
                ('from_account', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('proof', models.FileField(upload_to='proofs/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
